# Generated by Django 4.0.1 on 2024-03-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        ("knox", "0008_remove_authtoken_salt"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="AuthToken",
            name="salt_1",
        )
    ]
