# Generated by Django 4.0.1 on 2023-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_activity_user_delete_location_delete_userdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
    ]
