# Generated by Django 4.0.1 on 2023-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_activity_importance_level_alter_category_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_planned',
        ),
        migrations.AlterField(
            model_name='activity',
            name='importance_level',
            field=models.CharField(choices=[('M', 'Must'), ('S', 'Should'), ('C', 'Could'), ('W', "Won't"), ('N', 'None'), ('n', 'None')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='importance_level',
            field=models.CharField(choices=[('M', 'Must'), ('S', 'Should'), ('C', 'Could'), ('W', "Won't"), ('N', 'None'), ('n', 'None')], default='n', max_length=1),
        ),
    ]
