name: Docker Image for master

on:
  push:
    branches: [master]
    
jobs:
  test-image:
    uses: ./.github/workflows/docker-image-run.yml
    secrets: inherit
  publish-docker-image:
    needs: test-image
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker Image
      run: |
            docker buildx build -t ghcr.io/szade-organization/bettercalendar-api:latest .
            docker push ghcr.io/szade-organization/bettercalendar-api:latest
    
