name: Test Docker Image

on:
  pull_request:
    branches:
    - master**
  workflow_call:

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
  test-docker-image:
    needs: tests
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Build the Docker Image
      run: |
            docker buildx build -t ghcr.io/szade-organization/bettercalendar-api:latest .
            docker run -itd -e SECRET_KEY='${{ secrets.SECRET_KEY }}' -e BC_DB_CONNECTION_STRING='${{ secrets.DB_CONNECTION_STRING }}' ghcr.io/szade-organization/bettercalendar-api:latest 
    
