name: API full test

on:
  pull_request:
    branches: []
  push:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
        mongodb-version: ['7.0.4']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: user
        mongodb-password: password
    - name: Run full test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY}}
        BC_DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
      run: |
        cd config
        python manage.py test
