name: Test and Report to Azure Boards

on:
  push:
    branches: [master]  # Adjust this to your main branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Adjust the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '7.0.4'
          mongodb-username: user
          mongodb-password: password
      - name: Run tests
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
          AZURE_DEVOPS_URL: https://dev.azure.com/01169631/mwo5  # Replace with your Azure DevOps organization URL
          AZURE_DEVOPS_PROJECT: mwo5 # Replace with your Azure DevOps project name
          SECRET_KEY: ${{ secrets.SECRET_KEY}}
          BC_DB_CONNECTION_STRING: mongodb://user:password@localhost/?retryWrites=true&w=majority
          
        run: |
          cd config
          python manage.py test

      - name: Report to Azure Boards
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}

      - name: Create Work Item
        run: |
          az boards work-item create --type Bug --title "Error running the test" --description "Detailed description of the issue"


