name: Run tests

on:
  pull_request:
    branches: []
  push:
    branches: []
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and run tests
      uses: sdispater/poetry-action@v2
      with:
        python-version: ${{ matrix.python-version }}
        install-with-poetry: true
        poetry-version: '>=1.1.0'
        poetry-install-options: '--no-interaction --no-ansi'
      env:
        BC_DB_CONNECTION_STRING: mongodb://user:password@localhost/?retryWrites=true&w=majority
        SECRET_KEY: ${{ secrets.SECRET_KEY}}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '7.0.4'
        mongodb-username: user
        mongodb-password: password
    - name: Run full test
      run: |
        cd config
        poetry run python manage.py test
